appointment/urls.py
from django.urls import path

from appointment.apps import AppointmentConfig
from appointment.views import (
    appointments_detail,
    appointments_list,
    step_1,
    step_2,
    step_3,
    step_4,
)

appname = AppointmentConfig.name

urlpatterns = [
    path('appointment/step-1/', step_1, name='step-1'),
    path('appointment/step-2/', step_2, name='step-2'),
    path('appointment/step-3/', step_3, name='step-3'),
    path('appointment/step-4/', step_4, name='step-4'),
    path('appointment-list/', appointments_list, name='appointment-list'),
    path(
        'appointment-detail/<int:pk>/', appointments_detail, name='appointment-detail'
    ),
]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogDetailView, BlogListView

appname = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('view-blog/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
]

cart/urls.py
from django.urls import path
from cart.apps import CartConfig
from cart.views import cart_add, cart_detail, cart_remove

appname = CartConfig.name

urlpatterns = [
    path('cart/', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    ]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('optics.urls', namespace='optics')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('', include(('appointment.urls', 'appointment'), namespace='appointment')),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('', include(('cart.urls', 'cart'), namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

optics/urls.py
from django.urls import path

from optics.apps import OpticsConfig
from optics.views import (
    FeedbackCreateView,
    about,
    main_page,
    product_list_view,
    service_detail_view,
    service_list_view,
    thank_you,
)

app_name = OpticsConfig.name

urlpatterns = [
    path('', main_page, name='home'),
    path('contact/', FeedbackCreateView.as_view(), name='contact'),
    path('thank-you/', thank_you, name='thank-you'),
    path('about/', about, name='about'),
    path('shop-list/', product_list_view, name='shop-list'),
    path('service-list/', service_list_view, name='service-list'),
    path('service-detail/<int:pk>/', service_detail_view, name='service-detail'),
]

optics/models.py
from django.db import models

from config.settings import NULLABLE
from users.models import User


class Brand(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    ordering = ['name']

    class Meta:
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'
        ordering = ['name']

    def __str__(self):
        return f"{self.name}"


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(blank=True, verbose_name='Описание')
    is_published = models.BooleanField(default=False, verbose_name='Активно')
    active_on_main_page = models.BooleanField(
        default=False, verbose_name='Активно на гл.стр.'
    )

    ordering = ['name']

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    brand = models.ForeignKey(
        to=Brand,
        on_delete=models.PROTECT,
        related_name='products',
        verbose_name='Бренд',
        **NULLABLE,
    )
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    price = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='Цена')
    image = models.ImageField(
        upload_to='products/', **NULLABLE, verbose_name='Изображение'
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Изменен')
    category = models.ForeignKey(
        to=Category,
        on_delete=models.PROTECT,
        related_name='products',
        verbose_name='Категория',
    )
    owner = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        **NULLABLE,
        related_name='products',
        verbose_name='Владелец',
    )
    parameter = models.CharField(max_length=30, verbose_name='Параметр', **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='Активно')
    # manufactured_at = models.DateField(default=datetime.datetime(2024,4,21))

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name']

    def __str__(self):
        return f"{self.name}"


class Service(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='Цена')
    duration = models.PositiveSmallIntegerField(**NULLABLE, verbose_name='Длительность')
    image = models.ImageField(
        upload_to='products/', **NULLABLE, verbose_name='Изображение'
    )
    is_published = models.BooleanField(default=False, verbose_name='Публиковать')
    medic = models.ManyToManyField("users.User", related_name="services")

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'
        ordering = ['name']

    def __str__(self):
        return f"{self.name}"

tunes/models.py
from django.db import models

from config.settings import NULLABLE


class Feedback(models.Model):
    name = models.CharField(max_length=30, verbose_name='Имя')
    phone = models.CharField(max_length=20, verbose_name='Телефон', **NULLABLE)
    message = models.TextField(blank=True, verbose_name='Сообщение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    is_read = models.BooleanField(default=False, verbose_name='Прочитано')
    is_published = models.BooleanField(default=False, verbose_name='Публиковать')

    def __str__(self):
        return f"{self.name}, {self.created_at}"

    class Meta:
        # db_table = 'optics_feedback'
        ordering = ['-created_at']
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class Quote(models.Model):
    name = models.CharField(max_length=150, verbose_name='Имя')
    quote = models.TextField(blank=True, verbose_name='Цитата')
    is_published = models.BooleanField(default=False, verbose_name='Публиковать')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        # db_table = 'optics_quote'
        verbose_name = 'Цитата'
        verbose_name_plural = 'Цитаты'


class Contact(models.Model):
    country = models.CharField(max_length=50, verbose_name='Страна')
    inn = models.CharField(max_length=20, verbose_name='ИНН')
    address = models.CharField(max_length=255, verbose_name='Адрес')
    phone = models.CharField(max_length=30, verbose_name='Телефон')
    email = models.EmailField(verbose_name='Эл.почта')
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False, verbose_name='Активно')


    def __str__(self):
        return f"{self.email}"

    class Meta:
        # db_table = 'optics_contact'
        ordering = ['-updated_at']
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class TunesDict(models.Model):
    key = models.CharField(max_length=30, unique=True, verbose_name='Ключ')
    value_int = models.CharField(**NULLABLE, verbose_name='Целочисленное значение')
    value_char = models.CharField(max_length=100, **NULLABLE,  verbose_name='Строковое значение')
    value_time = models.TimeField( **NULLABLE,  verbose_name='Константа времени')
    value_date = models.DateField( **NULLABLE,  verbose_name='Константа даты')

    class Meta:
        ordering = ['key']
        verbose_name = 'Тонкие настройки'
        verbose_name_plural = 'Тонкие настройки'

    def __str__(self):
        return f"{self.key}"


class Banner(models.Model):
    title = models.CharField(max_length=300, verbose_name='Заголовок')
    content = models.TextField(**NULLABLE, verbose_name='Описание')
    image = models.ImageField(
        upload_to='tunes/', **NULLABLE, verbose_name='Изображение'
    )
    is_published = models.BooleanField(default=False, verbose_name='Активно')

    class Meta:
        ordering = ['title']
        verbose_name = 'Заглавный баннер'
        verbose_name_plural = 'Заглавные баннеры'

    def __str__(self):
        return f"{self.title}"

    @property
    def short_content(self):
        return f"{self.content[:40]} ..."

optics/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, ListView
from django.core.paginator import Paginator

from blog.models import Blog
from config.settings import MAIN_STREAMER_PATH, NUMBER_OF_PRODUCTS_DISPLAYED, SERVICE_PER_PAGE, PRODUCT_PER_PAGE
from optics.models import Category, Product, Service
from optics.src.utils import get_random_quote, get_random_reviews
from tunes.models import Feedback, TunesDict, Banner


# @cache_page(600)
def main_page(request):

    banner_list = Banner.objects.filter(is_published=True)

    category_list = Category.objects.filter(is_published=True)

    object_list = []
    for cat in category_list:
        product_set = Product.objects.filter(is_published=True, category=cat).order_by(
            '?'
        )
        product_list = product_set[:NUMBER_OF_PRODUCTS_DISPLAYED]
        obj = {'category': cat, 'product_list': product_list}
        object_list.append(obj)

    service_set = Service.objects.filter(is_published=True).order_by('?')
    service_list = service_set[:NUMBER_OF_PRODUCTS_DISPLAYED]

    blog_set = Blog.objects.filter(is_published=True).order_by('?')
    blog_list = blog_set[:3]

    context = {
        'object_list': object_list,
        'category_list': category_list,
        'service_list': service_list,
        'blog_list': blog_list,
        'testimonials': get_random_reviews(request),
        'quote': get_random_quote(request),
        'banner_list': banner_list,
    }

    return render(request, 'optics/index.html', context)


class FeedbackCreateView(CreateView):
    model = Feedback
    fields = ['name', 'phone', 'message']
    template_name = 'optics/contact.html'
    success_url = reverse_lazy('optics:thank-you')

    streamer_content = {'title': "Контакты"}
    streamer_path = MAIN_STREAMER_PATH.copy()
    streamer_path.append({'name': "Контакты", 'url': "#"})
    streamer_content['path'] = streamer_path
    extra_context = {
        'streamer_content': streamer_content,
    }


# @cache_page(600)
def product_list_view(request):

    category_list = Category.objects.filter(is_published=True)

    object_list = []
    for cat in category_list:
        product_list = Product.objects.filter(is_published=True, category=cat).order_by(
            'name'
        )
        paginator = Paginator(product_list, PRODUCT_PER_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        # obj = {'category': cat, 'product_list': product_list}
        obj = {'category': cat, 'page_obj': page_obj}
        object_list.append(obj)

    streamer_content = {'title': "Наши товары"}
    streamer_path = MAIN_STREAMER_PATH.copy()
    streamer_path.append({'name': "Магазин", 'url': "#"})
    streamer_content['path'] = streamer_path

    context = {
        'object_list': object_list,
        'category_list': category_list,
        'testimonials': get_random_reviews(request),
        'quote': get_random_quote(request),
        'streamer_content': streamer_content,
    }

    return render(request, 'optics/shop_list.html', context)


@cache_page(600)
def service_list_view(request):

    object_list = Service.objects.filter(is_published=True).order_by('name')

    paginator = Paginator(object_list, SERVICE_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    streamer_content = {'title': "Наши услуги"}
    streamer_path = MAIN_STREAMER_PATH.copy()
    streamer_path.append({'name': "Услуги", 'url': "#"})
    streamer_content['path'] = streamer_path

    context = {
        'testimonials': get_random_reviews(request),
        'quote': get_random_quote(request),
        'streamer_content': streamer_content,
        'page_obj': page_obj,
    }

    return render(request, 'optics/service_list.html', context)


@cache_page(600)
def service_detail_view(request, pk):

    obj = Service.objects.filter(pk=pk).first()

    streamer_content = {'title': "Наши услуги"}
    streamer_path = MAIN_STREAMER_PATH.copy()
    streamer_path.append({'name': "Услуги", 'url': "optics:service-list"})
    streamer_path.append(
        {
            'name': 'Текущая',
        }
    )
    streamer_content['path'] = streamer_path

    context = {
        'object': obj,
        'testimonials': get_random_reviews(request),
        'quote': get_random_quote(request),
        'streamer_content': streamer_content,
    }

    return render(request, 'optics/service_detail.html', context)


@cache_page(600)
def thank_you(request):
    context = {}

    return render(request, 'optics/thank-you.html', context=context)


@cache_page(600)
def about(request):
    streamer_content = {'title': "ОПТИКA СИТИ"}
    streamer_path = MAIN_STREAMER_PATH.copy()
    streamer_path.append({'name': "О нас", 'url': "#"})
    streamer_content['path'] = streamer_path

    context = {
        'testimonials': get_random_reviews(request),
        'streamer_content': streamer_content,
    }

    return render(request, 'optics/about.html', context=context)

optics/templates/optics/about.html
{% extends 'basic.html' %}

{% block content %}
{% load static %}

  {% include 'streamer.html' %}

  {% include 'shipping-info.html' %}

    <section id="about-us">
      <div class="container ">
        <div class="row d-flex align-items-center">
          <div class="col-lg-6 col-md-12">
            <div class="image-holder">
              <img src="{% static 'optics/images/single-image1.png' %}" alt="single" class="about-image">
            </div>
          </div>
          <div class="col-lg-6 col-md-12">
            <div class="">
              <div class="section-title">
                <h3>ОПТИКА СИТИ</h3>
                <h4>почему выбирают нас</h4>
                <p>	Наша приверженность совершенству начинается с инвестиций в современное оборудование. Мы понимаем, что точность и аккуратность имеют первостепенное значение в офтальмологии, поэтому мы оснастили наши учреждения новейшими достижениями в области оптических технологий. Это позволяет нам предлагать комплексные проверки зрения, точные рецепты и широкий ассортимент очков, адаптированных к уникальным потребностям каждого клиента.
                <br>
                <br>
					В ОПТИКА СИТИ считают, что каждая пара глаз так же уникальна, как и человек, который смотрит через них. Вот почему мы применяем индивидуальный подход к уходу за глазами. Наша команда уделяет время изучению вашего образа жизни, предпочтений и особых потребностей в области зрения. Независимо от того, являетесь ли вы спортсменом, профессионалом или ценителем модных очков, мы подбираем варианты, которые идеально соответствуют вашему индивидуальному стилю и требованиям.
                <br>
				<br>
					Смотря в будущее, ОПТИКА СИТИ по-прежнему стремится расширять границы возможного в области ухода за глазами. Наша история — это история постоянной эволюции, движимая нашим желанием предоставить лучшее для наших клиентов. Мы гордимся тем, что создали наследие доверия и качества, и мы стремимся поддерживать эти стандарты на протяжении многих лет. </p>
                <div class="btn-wrap">
                  <a href="{% url 'optics:service-list' %}" type="button" class="btn btn-grey btn-full" tabindex="0">Запишитесь на проверку<i class="icon icon-arrow-io"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}

optics/templates/optics/index.html
{% extends 'basic.html' %}

{% block content %}
{% load static %}
{% load optics_tags %}
<section id="billboard" class="overflow-hidden">

    <button class="button-prev">
        <i class="icon icon-chevron-left"></i>
    </button>
    <button class="button-next">
        <i class="icon icon-chevron-right"></i>
    </button>
    <div class="swiper main-swiper">
        <div class="swiper-wrapper">
            {% for banner in banner_list %}
            <div class="swiper-slide"
                 style="background-image: url('\
                        {% if banner.image %} \
                        {{ banner.image|add_media }} \
                        {% endif %} \
                        ');background-repeat: no-repeat;background-size: cover;background-position: center;">
                <div class="banner-content">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                <h2 class="banner-title">{{ banner.title }}</h2>
                                <p>{{ banner.content }}</p>
                                <div class="btn-wrap">
                                    <a href="{% url 'optics:shop-list' %}" class="btn btn-light btn-medium d-flex align-items-center"
                                       tabindex="0">За покупками <i class="icon icon-arrow-io"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% include 'shipping-info.html' %}

<section id="featured-products" class="product-store padding-large no-padding-top">
    <div class="container">
        <div class="section-header d-flex flex-wrap align-items-center justify-content-between">
            <h2 class="section-title">Наши услуги</h2>
            <div class="btn-wrap">
                <a href="{% url 'optics:service-list' %}" class="d-flex align-items-center">Посмотреть все услуги <i
                        class="icon icon icon-arrow-io"></i></a>
            </div>
        </div>
        <div class="row d-flex flex-wrap">
            {% for service in service_list %}
            <div class="product-item col-lg-3 col-md-6 col-sm-6">
                <div class="image-holder">
                    {% if service.image %}
                    <img class="card-img-left img-thumbnail" src="{{ service.image|add_media }}">
                    {% endif %}
                </div>
                <div class="cart-concern">
                    <div class="cart-button d-flex justify-content-between align-items-center">
                        <a href="{% url 'appointment:step-1' %}?service_pk={{ service.pk }}"
                           class="btn-wrap cart-link d-flex align-items-center" role="button">записаться
                            <i class="icon icon-arrow-io"></i>
                        </a>
                    </div>
                </div>
                <div class="product-detail">
                    <h4 class="product-title">
                        <a href="{% url 'optics:service-detail' service.pk %}">{{ service.name }}</a>
                    </h4>
                    <div class="item-price text-primary">P {{ service.price }}</div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% include 'testimonials.html' %}

<section id="selling-products" class="product-store bg-light-grey padding-large no-padding-top">
    <div class="container">
        <div class="section-header d-flex flex-wrap align-items-center justify-content-between">
            <h2 class="section-title">Наши товары</h2>
            <div class="btn-wrap">
                <a href="{% url 'optics:shop-list' %}" class="d-flex align-items-center">Посмотреть все товары <i
                        class="icon icon icon-arrow-io"></i></a>
            </div>
        </div>
        <ul class="tabs list-unstyled">
            {% for category in category_list %}
            <li data-tab-target="#{{ category.name }}" class="tab">{{ category.name }}</li>
            {% endfor %}
        </ul>
        <div class="tab-content">
            {% for object in object_list %}
            <div id="{{ object.category.name }}" data-tab-content {% if object.category.active_on_main_page %}
                 class="active" {% endif %}>
                <div class="row d-flex flex-wrap">
                    {% for product in object.product_list %}
                    <div id="product_{{ product.pk }}" class="product-item col-lg-3 col-md-6 col-sm-6">
                        <div class="image-holder">
                            {% if product.image %}
                            <img class="card-img-left img-thumbnail" src="{{ product.image|add_media }}">
                            {% endif %}
                        </div>
                        <div class="cart-concern">
                            <div class="cart-button d-flex justify-content-between align-items-center">
                                <a href="{% url 'cart:cart_add' product.pk %}" type="button" class="btn-wrap cart-link d-flex align-items-center">добавить в корзину
                                    <i class="icon icon-arrow-io"></i>
                                </a>
                            </div>
                        </div>
                        <div class="product-detail">
                            <h3 class="product-title">
                                <a>{{ product.brand }}</a>
                            </h3>
                            <h4 class="product-title">
                                <a href="single-product.html">{{ product.name }}</a>
                            </h4>
                            <div class="item-price text-primary">P {{ product.price }}</div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% include 'quotation.html' %}

<section id="latest-blog" class="padding-large no-padding-top">
    <div class="container">
        <div class="section-header d-flex flex-wrap align-items-center justify-content-between">
            <h2 class="section-title">Наш блог</h2>
            <div class="btn-wrap align-right">
                <a href="{% url 'blog:blog_list' %}" class="d-flex align-items-center">Все статьи <i
                        class="icon icon icon-arrow-io"></i>
                </a>
            </div>
        </div>
        <div class="row d-flex flex-wrap">
            {% for object in blog_list %}
            <article class="col-md-4 post-item">
                <div class="image-holder zoom-effect">
                    <a href="{% url 'blog:blog_detail' object.slug %}">
                        {% if object.image %}
                        <img class="card-img-left img-thumbnail" src="{{ object.image|add_media }}">
                        {% endif %}
                    </a>
                </div>
                <div class="post-content d-flex">
                    <div class="meta-date">
                        <div class="meta-day text-primary">{{object.created_at|date:'d'}}</div>
                        <div class="meta-month">{{object.created_at|date:'b-Y'}}</div>
                    </div>
                    <div class="post-header">
                        <h3 class="post-title">
                            <a href="{% url 'blog:blog_detail' object.slug  %}">{{ object.title }}</a>
                        </h3>
                        <a class="blog-categories">{{ object.short_content }}</a>
                    </div>
                </div>
            </article>
            {% endfor %}
        </div>
    </div>
</section>


{% endblock content %}

optics/templates/optics/service_detail.html
{% extends 'basic.html' %}

{% block content %}
{% load static %}
{% load optics_tags %}

{% include 'streamer.html' %}
{% include 'shipping-info.html' %}

<div class="main-content d-flex flex-wrap padding-large">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="post-meta">
                    <span class="post-date">{{ object.price }} P</span> / <a href="{% url 'appointment:step-1' %}?service_pk={{ object.pk }}" class="service-link link-success">Записаться</a>
                </div>
                <h1 class="page-title">{{ object.title }}</h1>
                <div class="feature-image">
                    {% if object.image %}
                    <img class="card-img-left img-thumbnail" src="{{ object.image|add_media }}">
                    {% endif %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="post-content">
                    <p>{{ object.description }}</p>
                    <div class="social-links d-flex margin-small">
                        <div class="element-title">Поделиться:</div>
                        <ul class="d-flex list-unstyled">
                            <li>
                                <a href="#"><i class="icon icon-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="icon icon-twitter"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="icon icon-instagram"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="icon icon-youtube-play"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

optics/templates/optics/service_list.html
{% extends 'basic.html' %}

{% block content %}
{% load static %}
{% load optics_tags %}

{% include 'streamer.html' %}
{% include 'shipping-info.html' %}

<section id="services" class="product-store padding-large">
    <div class="container">
        <div class="row d-flex flex-wrap">
            {% for service in page_obj %}
            <div class="product-item col-lg-3 col-md-6 col-sm-6">
                <div class="image-holder">
                    {% if service.image %}
                    <img class="card-img-left img-thumbnail" src="{{ service.image|add_media }}">
                    {% endif %}
                </div>
                <div class="cart-concern">
                    <div class="cart-button d-flex justify-content-between align-items-center">
                        <a href="{% url 'appointment:step-1' %}?service_pk={{ service.pk }}" class="btn-wrap cart-link d-flex align-items-center" role="button" >записаться
                            <i class="icon icon-arrow-io"></i>
                        </a>
                    </div>
                </div>
                <div class="product-detail">
                    <h4 class="product-title">
                        <a href="{% url 'optics:service-detail' service.pk %}">{{ service.name }}</a>
                    </h4>
                    <div class="item-price text-primary">P {{ service.price }}</div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% include 'page-panel.html' %}
</section>


{% endblock content %}