appointment/urls.py
from django.urls import path

from appointment.apps import AppointmentConfig
from appointment.views import (
    appointments_detail,
    appointments_list,
    step_1,
    step_2,
    step_3,
    step_4,
)

appname = AppointmentConfig.name

urlpatterns = [
    path('appointment/step-1/', step_1, name='step-1'),
    path('appointment/step-2/', step_2, name='step-2'),
    path('appointment/step-3/', step_3, name='step-3'),
    path('appointment/step-4/', step_4, name='step-4'),
    path('appointment-list/', appointments_list, name='appointment-list'),
    path(
        'appointment-detail/<int:pk>/', appointments_detail, name='appointment-detail'
    ),
]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogDetailView, BlogListView

appname = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('view-blog/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('optics.urls', namespace='optics')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('', include(('appointment.urls', 'appointment'), namespace='appointment')),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('', include(('cart.urls', 'cart'), namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointment/models.py
from django.db import models

from config.settings import DEFAULT_BEGIN_TIME, DEFAULT_END_TIME, NULLABLE
from optics.models import Service
from users.models import User

weekdays = ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс']

class Eye(models.Model):
    sph = models.DecimalField(
        **NULLABLE, max_digits=5, decimal_places=2, verbose_name='SPH'
    )
    cyl = models.DecimalField(
        **NULLABLE, max_digits=5, decimal_places=2, verbose_name='CYL'
    )
    ax = models.DecimalField(
        **NULLABLE, max_digits=5, decimal_places=2, verbose_name='AX'
    )
    pr = models.DecimalField(
        **NULLABLE, max_digits=5, decimal_places=2, verbose_name='Pr'
    )
    bas = models.DecimalField(
        **NULLABLE, max_digits=5, decimal_places=2, verbose_name='BAS'
    )
    dp = models.DecimalField(
        **NULLABLE, max_digits=5, decimal_places=2, verbose_name='DP'
    )
    add = models.DecimalField(
        **NULLABLE, max_digits=5, decimal_places=2, verbose_name='ADD'
    )

    class Meta:
        verbose_name = 'Результат измерений'
        verbose_name_plural = 'Результаты измерений'

    def __str__(self):
        return f"sph {self.sph} .."


class ResultOfService(models.Model):
    od = models.OneToOneField(
        to=Eye,
        **NULLABLE,
        on_delete=models.CASCADE,
        verbose_name='OD',
        related_name='od',
    )
    os = models.OneToOneField(
        to=Eye,
        **NULLABLE,
        on_delete=models.CASCADE,
        verbose_name='OS',
        related_name='os',
    )
    recommendations = models.TextField(blank=True, verbose_name='Рекомендации')
    comment = models.TextField(blank=True, verbose_name='Комментарий')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Изменен')

    class Meta:
        verbose_name = 'Результат услуги'
        verbose_name_plural = 'Результаты услуг'
        ordering = ['-created_at']

    def __str__(self):
        return f"OD: {self.od}, OS: {self.os}"


class Appointment(models.Model):
    day = models.DateField(verbose_name='День')
    time = models.TimeField(verbose_name='Время')
    comment = models.CharField(max_length=100, **NULLABLE, verbose_name='Комментарий')
    owner = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        **NULLABLE,
        related_name='appointments',
        verbose_name='Владелец',
    )
    service = models.ForeignKey(
        to=Service,
        on_delete=models.SET_NULL,
        **NULLABLE,
        related_name='appointments',
        verbose_name='Услуга',
    )
    medic = models.ForeignKey(
        to=User, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Медик'
    )
    result = models.OneToOneField(
        to=ResultOfService,
        **NULLABLE,
        on_delete=models.CASCADE,
        related_name='appointment',
        verbose_name='Результат',
    )

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        ordering = ['service', 'day', 'time']

    def __str__(self):
        return f"{self.owner} {self.service} ({self.day})"


class Schedule(models.Model):
    day = models.DateField(verbose_name='День')
    begin_time = models.TimeField(
        default=DEFAULT_BEGIN_TIME, verbose_name='Начало приема'
    )
    end_time = models.TimeField(default=DEFAULT_END_TIME, verbose_name='Конец приема')
    is_working_day = models.BooleanField(default=True, verbose_name='Рабочий день')
    medic = models.ForeignKey(
        to='users.User',
        on_delete=models.CASCADE,
        related_name='shedules',
        verbose_name='Медик',
    )

    class Meta:
        verbose_name = 'Расписание'
        verbose_name_plural = 'Расписание'
        ordering = ['medic', 'day']

    def __str__(self):
        return f"{self.medic} {self.day} {self.begin_time} {self.end_time}"

    @property
    def day_of_week(self):
        return weekdays[self.day.weekday()]

appointment/forms.py
import datetime

from django import forms
from django.utils import timezone


class SecondStepForm(forms.Form):
    service_pk = forms.IntegerField(widget=forms.HiddenInput())
    medic_pk = forms.IntegerField(widget=forms.HiddenInput())
    appointment_day = forms.DateField(
        label='Выберите дату',
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'min': timezone.now().date().isoformat(),
                'max': (timezone.now().date() + datetime.timedelta(30)).isoformat(),
            }
        ),
    )


class ThirdStepForm(forms.Form):
    service_pk = forms.IntegerField(widget=forms.HiddenInput())
    medic_pk = forms.IntegerField(widget=forms.HiddenInput())
    appointment_day = forms.DateField(
        label='На дату',
        widget=forms.DateInput(attrs={'type': 'date', 'readonly': True}),
    )
    appointment_slot = forms.ChoiceField(label='Выберите время', choices=[])

appointment/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.utils import timezone

from appointment.forms import SecondStepForm, ThirdStepForm
from appointment.models import Appointment, ResultOfService
from appointment.src.celery_cmd import write_reminder
from appointment.src.utils import get_time_slots
from config.settings import MAIN_STREAMER_PATH
from optics.models import Service
from users.models import User


# Create your views here.
@login_required
def step_1(request):
    service_pk = request.GET.get('service_pk')
    service = Service.objects.filter(pk=service_pk).first()
    object_list = service.medic.all()

    context = {
        'service_pk': service_pk,
        'object_list': object_list,
    }

    return render(request, 'appointment/step_1.html', context)


@login_required
def step_2(request):
    service_pk = request.GET.get('service_pk')
    medic_pk = request.GET.get('medic_pk')
    appointment_day = request.GET.get('date')
    if appointment_day is None:
        appointment_day = timezone.now().date().isoformat()
    form = SecondStepForm(
        initial={
            'service_pk': service_pk,
            'medic_pk': medic_pk,
            'appointment_day': appointment_day,
        }
    )

    service = Service.objects.filter(pk=service_pk).first()
    medic = User.objects.filter(pk=medic_pk).first()

    context = {'form': form, 'service': service, 'medic': medic}

    return render(request, 'appointment/step_2.html', context)


@login_required
def step_3(request):
    if request.method == 'POST':
        form = SecondStepForm(request.POST)
        if form.is_valid():
            service = Service.objects.filter(pk=form.data.get('service_pk')).first()
            medic = User.objects.filter(pk=form.data.get('medic_pk')).first()
            day = form.data.get('appointment_day')

            next_form = ThirdStepForm(initial=form.data)
            next_form.fields['appointment_slot'].choices = get_time_slots(
                day, service, medic
            )

            context = {
                'form': next_form,
                'service': service,
                'medic': medic,
                'date': day,
            }
            return render(request, 'appointment/step_3.html', context)
        else:

            return redirect(request, 'appointment/step_2.html', form.data)


@login_required
def step_4(request):
    if request.method == 'POST':
        form = SecondStepForm(request.POST)
        if form.is_valid():
            service = Service.objects.filter(pk=form.data.get('service_pk')).first()
            medic = User.objects.filter(pk=form.data.get('medic_pk')).first()
            day = form.data.get('appointment_day')
            time = form.data.get('appointment_slot')
            owner = request.user

            appointment = Appointment.objects.create(
                day=day, time=time, service=service, owner=owner, medic=medic
            )

            write_reminder(owner.pk, appointment.pk)

            context = {'service': service, 'medic': medic, 'date': day, 'slot': time}
            return render(request, 'appointment/thank-you.html', context)
        else:

            return redirect(request, 'appointment/step_3.html', form.data)


def appointments_list(request):
    object_list = Appointment.objects.filter(owner=request.user)

    streamer_content = {'title': 'Медкарта'}
    streamer_path = MAIN_STREAMER_PATH.copy()
    streamer_path.append({'name': 'Записи', 'url': 'appointment:appointment-list'})
    streamer_content['path'] = streamer_path

    context = {
        'object_list': object_list,
        'streamer_content': streamer_content,
    }

    return render(request, 'appointment/appointment-list.html', context)


def appointments_detail(request, pk):

    streamer_content = {'title': 'Медкарта'}
    streamer_path = MAIN_STREAMER_PATH.copy()
    streamer_path.append({'name': 'Записи', 'url': 'appointment:appointment-list'})
    streamer_path.append(
        {
            'name': 'Текущая',
        }
    )
    streamer_content['path'] = streamer_path

    result = ResultOfService.objects.filter(pk=pk).first()

    context = {
        'streamer_content': streamer_content,
        'result': result,
    }

    return render(request, 'appointment/appointment-detail.html', context)

appointment/templates/appointment/appointment-detail.html
{% extends 'basic.html' %}

{% block content %}
{% load static %}
{% load optics_tags %}

{% include 'streamer.html' %}

<section id="results" class="product-store padding-large">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <hr>
                <h3>Результаты проверки зрения</h3>
                <table class="u-full-width">
                    <thead>
                    <tr>
                        <th></th>
                        <th>SPH</th>
                        <th>CYL</th>
                        <th>AX</th>
                        <th>Pr</th>
                        <th>BAS</th>
                        <th>DP</th>
                        <th>ADD</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>OD</td>
                        <td>{{ result.od.sph|default:"-" }}</td>
                        <td>{{ result.od.cyl|default:"-" }}</td>
                        <td>{{ result.od.ax|default:"-" }}</td>
                        <td>{{ result.od.pr|default:"-" }}</td>
                        <td>{{ result.od.bas|default:"-" }}</td>
                        <td>{{ result.od.dp|default:"-" }}</td>
                        <td>{{ result.od.add|default:"-" }}</td>
                    </tr>
                    <tr>
                        <td>OS</td>
                        <td>{{ result.os.sph|default:"-" }}</td>
                        <td>{{ result.os.cyl|default:"-" }}</td>
                        <td>{{ result.os.ax|default:"-" }}</td>
                        <td>{{ result.os.pr|default:"-" }}</td>
                        <td>{{ result.os.bas|default:"-" }}</td>
                        <td>{{ result.os.dp|default:"-" }}</td>
                        <td>{{ result.os.add|default:"-" }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        {% if result.recommendations %}
        <div class="row">
            <div class="col-md-12">
                <h3>Рекомендации</h3>
                <p>{{ result.recommendations }}</p>
            </div>
        </div>
        {% endif %}
    </div>
</section>
<hr>

{% include 'shipping-info.html' %}

{% endblock content %}

appointment/templates/appointment/appointment-list.html
{% extends 'basic.html' %}

{% block content %}
{% load static %}
{% load optics_tags %}

{% include 'streamer.html' %}

<section id="results" class="product-store padding-large">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <hr>
                <h3>Записи на прием и результаты</h3>
                <table class="u-full-width">
                    <thead>
                    <tr>
                        <th>Дата</th>
                        <th>Время</th>
                        <th>Услуга</th>
                        <th>Врач</th>
                        <th>Результат</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                    <tr>
                        <td>{{ object.day }}</td>
                        <td>{{ object.time }}</td>
                        <td>{{ object.service }}</td>
                        <td>{{ object.medic }}</td>
                        {% if object.result is None %}
                        <td>нет результатов</td>
                        {% else %}
                        <td><a href="{% url 'appointment:appointment-detail' object.result_id %}">
                            {{ object.result }}
                        </a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<hr>

{% include 'shipping-info.html' %}

{% endblock content %}

appointment/templates/appointment/step_1.html
{% extends 'basic.html' %}

{% block content %}
{% load static %}
{% load appointment_tags %}

<section id="staff" class="product-store padding-large">
    <div class="container">
        <div class="row d-flex flex-wrap">
            {% for object in object_list %}
            <div class="product-item col-lg-3 col-md-6 col-sm-6">
                <div class="image-holder">
                    {% if object.image %}
                    <img class="card-img-left img-fluid img-thumbnail" src="{{ object.image|add_media }}">
                    {% endif %}
                </div>
                <div class="cart-concern">
                    <div class="cart-button d-flex justify-content-between align-items-center">
                        <a href="{% url 'appointment:step-2' %}?service_pk={{ service_pk }}&medic_pk={{ object.pk }}"
                           role="button" class="btn-wrap cart-link d-flex align-items-center">записаться
                            <i class="icon icon-arrow-io"></i>
                        </a>
                    </div>
                </div>
                <div class="product-detail">
                    <h4 class="product-title">
                        <a href="#">{{ object.profession }}</a>
                    </h4>
                    <div class="item-price text-primary">{{ object.last_name }} {{ object.first_name }}</div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <nav class="navigation paging-navigation text-center padding-medium" role="navigation">
        <div class="pagination loop-pagination d-flex justify-content-center">
            <a href="#" class="pagination-arrow d-flex align-items-center">
                <i class="icon icon-arrow-left"></i>
            </a>
            <span aria-current="page" class="page-numbers current">1</span>
            <a class="page-numbers" href="#">2</a>
            <a class="page-numbers" href="#">3</a>
            <a href="#" class="pagination-arrow d-flex align-items-center">
                <i class="icon icon-arrow-right"></i>
            </a>
        </div>
    </nav>
</section>

{% include 'shipping-info.html' %}

{% endblock content %}

appointment/templates/appointment/step_2.html
{% extends 'basic.html' %}

{% block content %}
{% load static %}

<section id="thank-you" class="padding-large bg-light-grey">
    <div class="container">
        <div class="row">
            <div class="page-header col-md-6">
                <div class="section-header">
                    <h1 class="section-title">Запись на услугу</h1>
                    <div class="detail">
                        <h3>{{ service.name }}</h3>
                        <p> {{ medic.fio }} ({{ medic.profession }})</p>
                    </div>
                    <form action="{% url 'appointment:step-3' %}" method="post">
                        {% csrf_token %}
                        <p>{{ form.appointment_day.label }}: {{ form.appointment_day }}</p>
                        <div class="button-area col-md-10">
                            <button class="btn btn-dark btn-full" type="submit">Следующий шаг</button>
                            <a href="{% url 'appointment:step-1' %}?service_pk={{ service.pk }}"
                               type="button" class="btn btn-grey btn-full">Назад</a>
                        </div>
                        {{ form.service_pk }}
                        {{ form.medic_pk }}
                    </form>
                </div>
            </div>
            {% include 'contacts.html' %}
        </div>
    </div>
</section>

{% include 'shipping-info.html' %}

{% endblock content %}

appointment/templates/appointment/step_3.html
{% extends 'basic.html' %}

{% block content %}
{% load static %}

<section id="thank-you" class="padding-large bg-light-grey">
    <div class="container">
        <div class="row">
            <div class="page-header col-md-6">
                <div class="section-header">
                    <h1 class="section-title">Запись на услугу</h1>
                    <div class="detail">
                        <h3>{{ service.name }}</h3>
                        <p> {{ medic.fio }} ({{ medic.profession }})</p>
                    </div>
                    <form action="{% url 'appointment:step-4' %}" method="post">
                        {% csrf_token %}
                        <p>
                            {{ form.appointment_day.label }}: {{ form.appointment_day }}
                            {{ form.appointment_slot.label }}: {{ form.appointment_slot }}
                        </p>
                        <div class="button-area col-md-10">
                            <button class="btn btn-dark btn-full" type="submit">Записаться</button>
                            <a href="{% url 'appointment:step-2' %}?service_pk={{ service.pk }}&medic_pk={{ medic.pk }}&date={{ date }}"
                               type="button" class="btn btn-grey btn-full">Назад</a>
                        </div>
                        {{ form.service_pk }}
                        {{ form.medic_pk }}
                    </form>
                </div>
            </div>
            {% include 'contacts.html' %}
        </div>
    </div>

</section>

{% include 'shipping-info.html' %}

{% endblock content %}

appointment/templates/appointment/thank-you.html
{% extends 'basic.html' %}

{% block content %}
{% load static %}

    <section id="thank-you" class="padding-large bg-light-grey">
      <div class="container">
        <div class="row">
          <div class="page-header col-md-6">
            <div class="section-header">
              <h1 class="section-title">Вы записаны!</h1>
                    <div class="detail">
                        <h3>{{ service.name }}</h3>
                        <p> {{ medic.fio }} ({{ medic.profession }})</p>
                        <p>
                            На дату: {{ date }}
                            Время : {{ slot }}
                        </p>
                    </div>
            </div>
          </div>
          {% include 'contacts.html' %}
        </div>
      </div>

    </section>

  {% include 'shipping-info.html' %}

  {% endblock content %}