blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogDetailView, BlogListView

appname = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('view-blog/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
]

cart/urls.py
from django.urls import path
from cart.apps import CartConfig
from cart.views import cart_add, cart_detail, cart_remove

appname = CartConfig.name

urlpatterns = [
    path('cart/', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    ]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('optics.urls', namespace='optics')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('', include(('appointment.urls', 'appointment'), namespace='appointment')),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('', include(('cart.urls', 'cart'), namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

optics/urls.py
from django.urls import path

from optics.apps import OpticsConfig
from optics.views import (
    FeedbackCreateView,
    about,
    main_page,
    product_list_view,
    service_detail_view,
    service_list_view,
    thank_you,
)

app_name = OpticsConfig.name

urlpatterns = [
    path('', main_page, name='home'),
    path('contact/', FeedbackCreateView.as_view(), name='contact'),
    path('thank-you/', thank_you, name='thank-you'),
    path('about/', about, name='about'),
    path('shop-list/', product_list_view, name='shop-list'),
    path('service-list/', service_list_view, name='service-list'),
    path('service-detail/<int:pk>/', service_detail_view, name='service-detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 3)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.urls import reverse
from config.settings import LOGIN_URL
from optics.models import Product
from .cart import Cart
from .forms import CartAddProductForm


def cart_add(request, product_id):
    if request.user.is_authenticated:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        if request.method == 'POST':
            form = CartAddProductForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                cart.add(product=product, quantity = cd['quantity'], override_quantity = cd['override'])
        else:
            cart.add(product=product, quantity=1, )

        url = request.META.get('HTTP_REFERER') + "#product_" +str(product_id)
        return redirect(url)
    else:
        url = reverse(LOGIN_URL)+'?next='+request.META.get('HTTP_REFERER')+ "#product_" +str(product_id)
        return redirect(url)

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
                            'quantity': item['quantity'],
                            'override': True})
    return render(request, 'cart/cart-list.html', {'cart': cart})

# @require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

cart/templates/cart/cart-list.html
{% extends 'basic.html' %}

{% block content %}
{% load static %}
{% load cart_tags %}

{% include 'streamer.html' %}
{% include 'shipping-info.html' %}

<section id="card-list" class="product-store padding-small">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>Корзина</h3>
                <table class="u-full-width">
                    <thead>
                    <tr>
                        <th></th>
                        <th>Товар</th>
                        <th>Количество</th>
                        <th></th>
                        <th></th>
                        <th>Цена</th>
                        <th>Итого</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in cart %}
                    {% with product=item.product %}
                    <tr id="product_{{ product.pk }}">
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                {% if product.image %}
                                <img class="card-img-left" width="200" src="{{ product.image|add_media }}">
                                {% endif %} </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {% csrf_token %}
                        <td valign="bottom">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.override }}
                        </td>
                        <td>
                            <button class="btn btn-outline-primary btn-pill" type="submit">
                                Обновить
                            </button>
                        </td>
                        </form>
                        <td>
                            <a href="{% url 'cart:cart_remove' product.id %}">
                                Удалить
                            </a>
                        </td>
                        <td class="num">P{{ item.price }}</td>
                        <td class="num">P{{ item.total_price }}</td>
                    </tr>
                    {% endwith %}
                    {% endfor %}
                    <tr>
                        <td><h4>Всего</h4></td>
                        <td colspan="4"></td>
                        <td class="num"><h4>P{{ cart.get_total_price }}</h4></td>
                    </tr>
                    </tbody>
                </table>
                <p class="text-right">
                    <a href="{% url 'optics:shop-list' %}" class="btn btn-accent">Продолжить покупки</a>
                    <a href="#" class="btn btn-primary">Оформить заказ</a>
                </p>
            </div>
        </div>
    </div>
</section>
<hr>

{% endblock content %}