appointment/urls.py
from django.urls import path

from appointment.apps import AppointmentConfig
from appointment.views import (
    appointments_detail,
    appointments_list,
    step_1,
    step_2,
    step_3,
    step_4,
)

appname = AppointmentConfig.name

urlpatterns = [
    path('appointment/step-1/', step_1, name='step-1'),
    path('appointment/step-2/', step_2, name='step-2'),
    path('appointment/step-3/', step_3, name='step-3'),
    path('appointment/step-4/', step_4, name='step-4'),
    path('appointment-list/', appointments_list, name='appointment-list'),
    path(
        'appointment-detail/<int:pk>/', appointments_detail, name='appointment-detail'
    ),
]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogDetailView, BlogListView

appname = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('view-blog/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
]

cart/urls.py
from django.urls import path
from cart.apps import CartConfig
from cart.views import cart_add, cart_detail, cart_remove

appname = CartConfig.name

urlpatterns = [
    path('cart/', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    ]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('optics.urls', namespace='optics')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('', include(('appointment.urls', 'appointment'), namespace='appointment')),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('', include(('cart.urls', 'cart'), namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

optics/urls.py
from django.urls import path

from optics.apps import OpticsConfig
from optics.views import (
    FeedbackCreateView,
    about,
    main_page,
    product_list_view,
    service_detail_view,
    service_list_view,
    thank_you,
)

app_name = OpticsConfig.name

urlpatterns = [
    path('', main_page, name='home'),
    path('contact/', FeedbackCreateView.as_view(), name='contact'),
    path('thank-you/', thank_you, name='thank-you'),
    path('about/', about, name='about'),
    path('shop-list/', product_list_view, name='shop-list'),
    path('service-list/', service_list_view, name='service-list'),
    path('service-detail/<int:pk>/', service_detail_view, name='service-detail'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    LoginView,
    ProfileUpdateView,
    UserCreateView,
    confirm_user,
    logout_form,
)

appname = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('logout-form/', logout_form, name='logout_form'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('create-user/', UserCreateView.as_view(), name='create_user'),
    path('confirm/<str:token>', confirm_user, name='confirm'),
]

templates/basic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>ОПТИКА СИТИ - салон оптики</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="author" content="">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="{% static 'optics/css/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'optics/icomoon/icomoon.css' %}">
    <link rel="stylesheet" type="text/css" media="all"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'optics/css/vendor.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'optics/css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">
    <!-- script
    ================================================== -->
    <script src="{% static 'optics/js/modernizr.js' %}"></script>
</head>
<body>

<div class="preloader-wrapper">
    <div class="preloader">
    </div>
</div>

<header id="header" class="nav-fixed">
    <div id="header-wrap">
        <nav class="secondary-nav border-bottom">
            <div class="container">
                <div class="row d-flex align-items-center">
                    <div class="col-md-4 header-contact">
                        <p>Есть вопросы? <strong>{{contact.phone}}</strong>
                        </p>
                    </div>
                    <div class="col-md-4 shipping-purchase text-center">
                        <p>Бесплатная доставка при покупке от 10.000</p>
                    </div>
                    <div class="col-md-4 col-sm-12 user-items">
                        <ul class="d-flex justify-content-end list-unstyled">
                            {% if user.is_authenticated %}
                            <li>
                                <a title="Профиль" href="{% url 'users:profile' %}">
                                    <i class="icon icon-user"></i>
                                </a>
                            </li>
                            <li>
                                <a title="Моя медкарта" href="{% url 'appointment:appointment-list'%}">
                                    <i class="icon icon-heart"></i>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'cart:cart_detail'%}">
                                    <i class="icon icon-shopping-cart"></i>
                                    {% if cart|length > 0 %}
                                        {{ cart|length }}
                                    {% endif %}
                                </a>
                            </li>
                            <li>
                                <a title="Выйти" href="{% url 'users:logout_form' %}">
                                    <i class="icon icon-cancel"></i>
                                </a>
                            </li>
                            {% else %}
                            <li>
                                <a title="Войти" href="{% url 'users:login' %}">
                                    <i class="icon icon-user"></i>
                                </a>
                            </li>
                            {% endif %}
                            <!--                  <li class="user-items search-item pe-3">-->
                            <!--                    <a href="#" class="search-button">-->
                            <!--                      <i class="icon icon-search"></i>-->
                            <!--                    </a>-->
                            <!--                  </li>-->
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        <nav class="primary-nav">
            <div class="container">
                <div class="row d-flex align-items-center">
                    <div class="col-lg-2 col-md-2">
                        <div class="main-logo">
                            <a href="{% url 'optics:home' %}">
                                <img src="{% static 'optics/images/main-logo.png' %}" alt="logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-10 col-md-10">
                        <div class="navbar">

                            <div id="main-nav" class="stellarnav d-flex justify-content-end right">
                                <ul class="menu-list">

                                    <li>
                                        <a href="{% url 'optics:home' %}" class="item-anchor d-flex align-item-center"
                                           data-effect="Home">Главная</a>
                                    </li>

                                    <li><a href="{% url 'optics:about' %}" class="item-anchor" data-effect="About">О
                                        компании</a></li>

                                    <li class="menu-item">
                                        <a href="{% url 'optics:shop-list'%}"
                                           class="item-anchor d-flex align-item-center" data-effect="Shop">Товары</a>
                                    </li>

                                    <li class="menu-item">
                                        <a href="{% url 'optics:service-list'%}"
                                           class="item-anchor d-flex align-item-center" data-effect="Pages">Услуги</a>
                                    </li>

                                    <li class="menu-item">
                                        <a href="{% url 'blog:blog_list' %}"
                                           class="item-anchor d-flex align-item-center" data-effect="Blog">Блог</a>
                                    </li>

                                    <li><a href="{% url 'optics:contact' %}" class="item-anchor" data-effect="Contact">Контакты</a>
                                    </li>

                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</header>
<div class="margin-content">

</div>
{% block content %}
{% endblock content %}

<footer id="footer">
    <div class="container">
        <div class="footer-menu-list">
            <div class="row d-flex flex-wrap justify-content-between">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-menu">
                        <h5 class="widget-title">ОПТИКА СИТИ</h5>
                        <ul class="menu-list list-unstyled">
                            <li class="menu-item">
                                <a href="about.html">О нас</a>
                            </li>
                            <li class="menu-item">
                                <a href="#">Conditions </a>
                            </li>
                            <li class="menu-item">
                                <a href="blog.html">Наш блог</a>
                            </li>
                            <li class="menu-item">
                                <a href="#">Вакансии</a>
                            </li>
                            <li class="menu-item">
                                <a href="#">Наши партнеры</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-menu">
                        <h5 class="widget-title">Поддержка</h5>
                        <ul class="menu-list list-unstyled">
                            <li class="menu-item">
                                <a href="faqs.html">FAQ</a>
                            </li>
                            <li class="menu-item">
                                <a href="contact.html">Контакты</a>
                            </li>
                            <li class="menu-item">
                                <a href="#">Политика защиты ПД</a>
                            </li>
                            <li class="menu-item">
                                <a href="#">Как вернуть</a>
                            </li>
                            <li class="menu-item">
                                <a href="#">Доставка</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-menu">
                        <h5 class="widget-title">Наши контакты</h5>
                        <p>У вас есть предложения? <a href="#" class="email">{{contact.email}}</a>
                        </p>
                        <p>У вас есть вопросы? Позвоните. <br>
                            <strong>{{contact.phone}}</strong>
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-menu">
                        <h5 class="widget-title">Forever 2018</h5>
                        <p>Cras mattis sit ornare in metus eu amet adipiscing enim. Ullamcorper in orci, ultrices
                            integer eget arcu. Consectetur leo dignissim lacus, lacus sagittis dictumst.</p>
                        <div class="social-links">
                            <ul class="d-flex list-unstyled">
                                <li>
                                    <a href="#">
                                        <i class="icon icon-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="icon icon-twitter"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="icon icon-youtube-play"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="icon icon-behance-square"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
</footer>

<div id="footer-bottom">
    <div class="container">
        <div class="d-flex align-items-center flex-wrap justify-content-between">
            <div class="copyright">
                <p>Freebies by <a href="https://templatesjungle.com/">Templates Jungle</a> Distributed by <a
                        href="https://themewagon.com">ThemeWagon</a>
                </p>
            </div>
            <div class="payment-method">
                <p>Payment options :</p>
                <div class="card-wrap">
                    <img src="{% static 'optics/images/visa-icon.jpg' %}" alt="visa">
                    <img src="{% static 'optics/images/mastercard.png' %}" alt="mastercard">
                    <img src="{% static 'optics/images/american-express.jpg' %}" alt="american-express">
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'optics/js/jquery-1.11.0.min.js' %}"></script>
<script src="{% static 'optics/js/plugins.js' %}"></script>
<script src="{% static 'optics/js/script.js' %}"></script>
</body>
</html>

templates/contacts.html
<div class="contact-information">
    <div class="col-md-6">
        <div class="section-header">
            <h2 class="section-title">Свяжитесь с нами</h2>
        </div>
        <div class="row">
            <div class="d-flex flex-wrap bg-light">
                <div class="col-md-6 border-right border-bottom">
                    <div class="detail">
                        <h3>Телефоны</h3>
                        <ul class="list-unstyled">
                            <li>
                                <i class="icon icon-phone"></i>{{ contact.phone }}
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6 border-bottom">
                    <div class="detail">
                        <h3>Почта</h3>
                        <ul class="list-unstyled">
                            <li>
                                <i class="icon icon-envelope"></i>
                                <a href="mailto:info@opticsystems.top">info@opticsystems.top</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6 border-right">
                    <div class="address detail">
                        <h3>Адрес</h3>
                        <ul class="list-unstyled">
                            <li>
                                <i class="icon icon-location"></i>
                                <span>г.Сафоново, Смоленская область, ул.Кирова 12</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="detail">
                        <h3>Social Links</h3>
                        <ul class="social-links list-unstyled d-flex">
                            <li><a href="#" class="icon icon-facebook"></a></li>
                            <li><a href="#" class="icon icon-twitter"></a></li>
                            <li><a href="#" class="icon icon-youtube-play"></a></li>
                            <li><a href="#" class="icon icon-behance-square"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/messages.html
<style>
    .alert{position:relative;padding:.75rem 1.25rem;margin-bottom:1rem;border:1px solid transparent;border-radius:.25rem}.alert-heading{color:inherit}.alert-link{font-weight:700}.alert-dismissible{padding-right:4rem}.alert-dismissible .close{position:absolute;top:0;right:0;padding:.75rem 1.25rem;color:inherit}.alert-primary{color:#004085;background-color:#cce5ff;border-color:#b8daff}.alert-primary hr{border-top-color:#9fcdff}.alert-primary .alert-link{color:#002752}.alert-secondary{color:#383d41;background-color:#e2e3e5;border-color:#d6d8db}.alert-secondary hr{border-top-color:#c8cbcf}.alert-secondary .alert-link{color:#202326}.alert-success{color:#155724;background-color:#d4edda;border-color:#c3e6cb}.alert-success hr{border-top-color:#b1dfbb}.alert-success .alert-link{color:#0b2e13}.alert-info{color:#0c5460;background-color:#d1ecf1;border-color:#bee5eb}.alert-info hr{border-top-color:#abdde5}.alert-info .alert-link{color:#062c33}.alert-warning{color:#856404;background-color:#fff3cd;border-color:#ffeeba}.alert-warning hr{border-top-color:#ffe8a1}.alert-warning .alert-link{color:#533f03}.alert-danger{color:#721c24;background-color:#f8d7da;border-color:#f5c6cb}.alert-danger hr{border-top-color:#f1b0b7}.alert-danger .alert-link{color:#491217}.alert-light{color:#818182;background-color:#fefefe;border-color:#fdfdfe}.alert-light hr{border-top-color:#ececf6}.alert-light .alert-link{color:#686868}.alert-dark{color:#1b1e21;background-color:#d6d8d9;border-color:#c6c8ca}.alert-dark hr{border-top-color:#b9bbbe}.alert-dark .alert-link{color:#040505}@-webkit-keyframes progress-bar-stripes{from{background-position:1rem 0}to{background-position:0 0}}@keyframes progress-bar-stripes{from{background-position:1rem 0}to{background-position:0 0}}
</style>

{% if messages %}
{% for message in messages %}
<div class="alert-container">
    <div class="alert alert-{{ message.tags }}" role="alert">
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}

templates/page-panel-product.html
<nav class="navigation paging-navigation text-center padding-medium" role="navigation">
    <div class="pagination loop-pagination d-flex justify-content-center">

        {% if object.page_obj.has_previous %}
        <li class="pagination-arrow d-flex align-items-center">
            <a href="?page={{ page_obj.previous_page_number }}"><i class="icon icon-arrow-left"></i></a>
        </li>
        {% endif %}

        {% for p in object.page_obj.paginator.page_range %}
        {% if object.page_obj.number == p %}
        <li class="page-numbers current">{{ p }}</li>
        {% elif p >= object.page_obj.number|add:-2 and p <= object.page_obj.number|add:2 %}
        <li class="page-numbers">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if object.page_obj.has_next %}
        <li class="pagination-arrow d-flex align-items-center">
            <a href="?page={{ page_obj.next_page_number }}"><i class="icon icon-arrow-right"></i></a>
        </li>
        {% endif %}

    </div>
</nav>

templates/page-panel.html
<nav class="navigation paging-navigation text-center padding-medium" role="navigation">
    <div class="pagination loop-pagination d-flex justify-content-center">

        {% if page_obj.has_previous %}
        <li class="pagination-arrow d-flex align-items-center">
            <a href="?page={{ page_obj.previous_page_number }}"><i class="icon icon-arrow-left"></i></a>
        </li>
        {% endif %}

        {% for p in page_obj.paginator.page_range %}
        {% if page_obj.number == p %}
        <li class="page-numbers current">{{ p }}</li>
        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
        <li class="page-numbers">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="pagination-arrow d-flex align-items-center">
            <a href="?page={{ page_obj.next_page_number }}"><i class="icon icon-arrow-right"></i></a>
        </li>
        {% endif %}

    </div>
</nav>

templates/quotation.html
<hr>
<section id="quotation" class="align-center no-padding-bottom">
      <div class="inner-content">
        <h2 class="section-title divider">Цитата дня</h2>
        <blockquote>
          <q>{{ quote.quote }}</q>
          <div class="author-name">- {{ quote.name }}</div>
        </blockquote>
      </div>
    </section>
<hr>

templates/shipping-info.html
<hr>
<section id="shipping-information" class="no-padding-bottom">
    <div class="container">
        <div class="row d-flex flex-wrap align-items-center justify-content-between">
            <div class="col-md-3 col-sm-6">
                <div class="icon-box">
                    <i class="icon icon-truck"></i>
                    <h4 class="block-title">
                        <strong>Бесплатная </strong> доставка
                    </h4>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="icon-box">
                    <i class="icon icon-return"></i>
                    <h4 class="block-title">
                        <strong>Гарантия</strong> 3 месяца
                    </h4>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="icon-box">
                    <i class="icon icon-tags1"></i>
                    <h4 class="block-title">
                        <strong>Скидки</strong> до 50% !
                    </h4>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="icon-box">
                    <i class="icon icon-help_outline"></i>
                    <h4 class="block-title">
                        <strong>Есть вопросы?</strong> ответим
                    </h4>
                </div>
            </div>
        </div>
    </div>
</section>
<hr>

templates/streamer.html
{% load static %}
<section class="site-banner jarallax min-height300 padding-large"
         style="background: url('{% static 'optics/images/hero-image.png' %}') no-repeat;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-title">{{streamer_content.title}}</h1>
                <div class="breadcrumbs">
                    {% for obj in streamer_content.path %}
                        {% if forloop.last %}
                            <span class="item">{{obj.name}}</span>
                        {% else %}
                            <span class="item">
                                <a href="{% url obj.url %}">{{obj.name}} /</a>
                            </span>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

templates/testimonials.html
<hr>
<section id="testimonials" class="padding-small no-padding-top">
    <div class="container">
        <div class="reviews-content">
            <div class="row d-flex flex-wrap">
                <div class="col-md-2">
                    <div class="review-icon">
                        <i class="icon icon-right-quote"></i>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="swiper testimonial-swiper overflow-hidden">
                        <div class="swiper-wrapper">
                            {% for testimonial in testimonials %}
                            <div class="swiper-slide">
                                <div class="testimonial-detail">
                                    <p>{{ testimonial.message }}</p>
                                    <div class="author-detail">
                                        <div class="name">{{ testimonial.name }}</div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="swiper-arrows">
                        <button class="prev-button">
                            <i class="icon icon-arrow-left"></i>
                        </button>
                        <button class="next-button">
                            <i class="icon icon-arrow-right"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<hr>